import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
font_paths = fm.findSystemFonts(fontpaths=None, fontext='ttf')
noto_fonts = [f for f in font_paths if 'NotoSansCJK' in f]
font_path = noto_fonts[0]
prop = fm.FontProperties(fname=font_path)
file_path = '/content/account_interaction_rates.csv'
df = pd.read_csv(file_path)
print(df.head())
df_sorted_likes = df.sort_values(by='平均点赞互动率', ascending=False)
df_sorted_comment = df.sort_values(by='平均评论互动率', ascending=False)
df_sorted_collect = df.sort_values(by='平均收藏互动率', ascending=False)
df_sorted_share = df.sort_values(by='平均分享互动率', ascending=False)
def plot_likes_rate(df):
    plt.figure(figsize=(12, 8))
    plt.plot(df['账号名'], df['平均点赞互动率'], label='平均点赞互动率', marker='o')
    plt.xlabel('账号名', fontproperties=prop)
    plt.ylabel('互动率', fontproperties=prop)
    plt.title('各账号的平均点赞互动率', fontproperties=prop)
    plt.xticks(rotation=90, fontproperties=prop)
    plt.legend(prop=prop)
    plt.tight_layout()
    plt.savefig('/content/account_likes_interaction_rates_plot.png')
    plt.show()
def plot_comment_rate(df):
    plt.figure(figsize=(12, 8))
    plt.plot(df['账号名'], df['平均评论互动率'], label='平均评论互动率', marker='o')
    plt.xlabel('账号名', fontproperties=prop)
    plt.ylabel('互动率', fontproperties=prop)
    plt.title('各账号的平均评论互动率', fontproperties=prop)
    plt.xticks(rotation=90, fontproperties=prop)
    plt.legend(prop=prop)
    plt.tight_layout()
    plt.savefig('/content/account_comment_interaction_rates_plot.png')
    plt.show()
def plot_collect_rate(df):
    plt.figure(figsize=(12, 8))
    plt.plot(df['账号名'], df['平均收藏互动率'], label='平均收藏互动率', marker='o')
    plt.xlabel('账号名', fontproperties=prop)
    plt.ylabel('互动率', fontproperties=prop)
    plt.title('各账号的平均收藏互动率', fontproperties=prop)
    plt.xticks(rotation=90, fontproperties=prop)
    plt.legend(prop=prop)
    plt.tight_layout()
    plt.savefig('/content/account_collect_interaction_rates_plot.png')
    plt.show()
def plot_share_rate(df):
    plt.figure(figsize=(12, 8))
    plt.plot(df['账号名'], df['平均分享互动率'], label='平均分享互动率', marker='o')
    plt.xlabel('账号名', fontproperties=prop)
    plt.ylabel('互动率', fontproperties=prop)
    plt.title('各账号的平均分享互动率', fontproperties=prop)
    plt.xticks(rotation=90, fontproperties=prop)
    plt.legend(prop=prop)
    plt.tight_layout()
    plt.savefig('/content/account_share_interaction_rates_plot.png')
    plt.show()
plot_likes_rate(df_sorted_likes)
plot_comment_rate(df_sorted_comment)
plot_collect_rate(df_sorted_collect)
plot_share_rate(df_sorted_share)
